src:
  codepath: "/home/raymond/CESMpy"

# Detail about the run
run:
  name: "LGM"
  folder: "/scratch-shared/raymond"
  plotdir: "/home/raymond/LGMplots"

# Specific to trend calculation and plotting
trend:
  significance: 0.05
  nyears: 30 # Can be "all", a number of years, or a range (tuple)

# Regions to calculate timeseries over
timeseries:
  regions: ["global", "NH", "SH", "tropical"]

# Runs to be analyzed
runs:
#  B-I-LGM-rest286-200729:
#    folder: "/projects/0/couplice/archive"
#  B-I-LGM-rest316-200804:
#    folder: "/projects/0/couplice/archive"
#  B-I-LGM-rest331-200814:
#    folder: "/projects/0/couplice/archive"
#  B-I-LGM-rest338-200817:
#    folder: "/projects/0/couplice/archive"
#  B-I-rest356-LGM-200828:
#    folder: "/projects/0/couplice/archive"
#  B-I-rest371-LGM-200902:
#    folder: "/projects/0/couplice/archive"
  B-I-rest428-LGM-200920:
    folder: "/projects/0/couplice/archive"

# History files
history:
  atm:
    h0:
      varlist: ["CLDHGH", "CLDLOW", "CLDMED", "CLDTOT", "FLDS", "FLNS", "FLNSC", "FLNT", "FSDS", "FSDSC", "FSNS", "FSNSC", "FSNT", "ICEFRAC", "LHFLX", "PRECC", "PRECL", "PRECSC", "PRECSL", "PSL", "SHFLX", "TGCLDCWP", "TGCLDIWP", "TMQ", "TS", "U250", "U500", "U850", "V250", "V500", "V850"]
      htype: "monavg"
    h1:
      varlist: ["LANDFRAC", "LWCF", "OCNFRAC", "QREFHT", "SWCF", "TREFHT", "U10", "SST"]
      htype: "monavg"
  ocn:
    h:
      varlist: ["TEMP"]
      htype: "monavg"

# Specific settings for components
compset:
  atm:
    bnds: "time_bnds"
