# Details about the machine
machine:
    codepath: "/home/raymond/CESMpy"
    directive: ["#SBATCH", "-N 1", "--time 01:00:00", "-p normal"]
    nproc: 24
    mpi: True
    condaact: "/home/raymond/miniconda3/bin/activate"
    condaenv: "LGM"

# Detail about the run
run:
    name: "LGM"
    folder: "/scratch-shared/raymond"
    plotdir: "/home/raymond/LGMplots"
  
# Runs to be analyzed
runs:
    B-I-LGM-rest286-200729:
        folder: "/projects/0/couplice/archive"

    
# Specific settings for components
compset:
  atm:
    bnds: "time_bnds"
  lnd:
    bnds: "time_bounds"
  ocn:
    bnds: "time_bound"
  ice:
    bnds: "time_bounds"
  
# History files
history:
  ts: False
  atm:
    h0:
      varlist: ["CLDHGH", "CLDLOW", "CLDMED", "CLDTOT", "FLDS", "FLNS", "FLNSC", "FLNT", "FSDS", "FSDSC", "FSNS", "FSNSC", "FSNT", "ICEFRAC", "LHFLX", "PRECC", "PRECL", "PRECSC", "PRECSL", "PSL", "SHFLX", "TGCLDCWP", "TGCLDIWP", "TMQ", "TS", "U250", "U500", "U850", "V250", "V500", "V850"]
      htype: "monavg"
    h1:
      varlist: ["LANDFRAC", "LWCF", "OCNFRAC", "QREFHT", "SWCF", "TREFHT", "U10", "SST"]
      htype: "monavg"
  ocn:
    h:
      varlist: ["TEMP"]
      htype: "monavg"

##########
# Script specific settings
##########

# Regions to calculate timeseries over
timeseries:
  regions: ["global", "NH", "SH", "tropical"]
  
# Specific to trend calculation and plotting
trend:
  significance: 0.05
  nyears: 30 # Can be "all", a number of years, or a range (tuple)
